name: Pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  main:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: build
        run: |
          npm i
          npm run build
          cp public/index.html dist/index.html
      - name: deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
